---
- name: Play to replace PermitRootLogin in /etc/ssh/sshd_config file
  hosts: 192.168.35.100
  gather_facts: no
  become: true
  remote_user: ansible
  tasks: 
  - name: Replace
    lineinfile:
     path: /etc/ssh/sshd_config
     regexp: ^PermitRootLogin
     line: "PermitRootLogin=yes"
     #line: "PermitRootLogin=no"
     backup: yes
  - name: Restart sshd daemon
    service:
     name: sshd
     state: restarted
...